### ISSUE TITLE
can't import com.tencent.tcr.sdk.api.TcrTestEnv

### ISSUE THREAD

**Issue by helloalvin** [tencentyun/cloudgame-android-sdk#10]
In SimpleDemo project, when i open with Android Studio.
in MainActivity, Line 22 report a "import error":
![image](https://github.com/tencentyun/cloudgame-android-sdk/assets/4996945/e2bcffd0-400b-49b9-ad32-e9cb8361d3b8)
the SDK Version is 【com.tencent.tcr:tcrsdk-full:3.8.2@aar】
how to fix this error,and i can continue?

**Comment by xxhapecheng** [comment]
Hi! @helloalvin , please upgrade the version of TcrSdk in app/build.gradle. Version records can be referred to https://github.com/tencentyun/cloudgame-android-sdk/blob/master/TcrSdk/Release_Notes.md
